// Real PDF and Excel generation for a Blueprint.
// PDF via pdfkit, Excel (.xlsx) via exceljs. Both return a Buffer.

import PDFDocument from "pdfkit";
import ExcelJS from "exceljs";
import { Blueprint, pega } from "./pega/store";

export function safeFileName(s: string): string {
  return s.replace(/[^a-z0-9._-]+/gi, "_").replace(/_+/g, "_").slice(0, 80) || "blueprint";
}

export function buildPdf(bp: Blueprint): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const accent = "#f25022";
    const h1 = (t: string) => doc.moveDown(0.6).fillColor(accent).fontSize(16).font("Helvetica-Bold").text(t).fillColor("black").font("Helvetica").fontSize(11);
    const para = (t: string) => doc.fontSize(11).font("Helvetica").fillColor("black").text(t, { align: "left" });
    const small = (t: string) => doc.fontSize(9).fillColor("#666666").text(t).fillColor("black");

    // Title block
    doc.fillColor(accent).fontSize(22).font("Helvetica-Bold").text("Customer Engagement Blueprint");
    doc.fillColor("black").fontSize(14).font("Helvetica").text(bp.title);
    small(`${bp.industry}  ·  ${bp.id}`);

    const s = pega.summary(bp.id);
    h1("Overview");
    para(`Organization: ${bp.orgName}   |   Website: ${bp.website}`);
    para(`Objective: ${bp.objective}`);
    para(`Language: ${bp.language}   |   Location: ${bp.location}`);
    para(`Outcomes: ${bp.outcomes.join(", ") || "—"}   |   Channels: ${bp.channels.join(", ") || "—"}`);
    para(`Actions: ${s.actions}   |   Messages: ${s.treatments}   |   Channels used: ${s.channels}`);

    h1("Objective details");
    para(bp.objectiveDetails);

    h1("Personas");
    if (bp.personas.length === 0) para("No personas generated.");
    for (const p of bp.personas) {
      doc.font("Helvetica-Bold").fontSize(12).text(p.name);
      doc.font("Helvetica").fontSize(9).fillColor("#666666").text([p.gender, p.ageBand].filter(Boolean).join(" · ")).fillColor("black");
      doc.fontSize(10).text(p.description, { align: "left" });
      doc.moveDown(0.4);
    }

    h1("Brand voice");
    const enabled = bp.voice.filter((v) => v.enabled);
    if (enabled.length === 0) para("No voice characteristics enabled.");
    for (const v of enabled) {
      doc.font("Helvetica-Bold").fontSize(11).text(`• ${v.name}`);
      doc.font("Helvetica").fontSize(10).fillColor("#444444").text(`   ${v.description}`).fillColor("black");
    }

    h1("Experiences (Actions & Treatments)");
    for (const a of bp.actions) {
      doc.moveDown(0.3).font("Helvetica-Bold").fontSize(12).text(`${a.name}`);
      doc.font("Helvetica").fontSize(9).fillColor("#666666").text(`${a.product} · ${a.objective}`).fillColor("black");
      doc.fontSize(10).text(a.description);
      for (const t of a.treatments) {
        doc.moveDown(0.2).font("Helvetica-Bold").fontSize(10).text(`   ${t.name}  [${t.channel}]`);
        doc.font("Helvetica").fontSize(10).text(`   Headline: ${t.headline}`);
        doc.fontSize(10).text(`   Message: ${t.body}`);
        doc.fontSize(10).text(`   CTA: ${t.cta}   |   Principle: ${t.marketingPrinciple ?? "—"}`);
      }
    }

    doc.moveDown(1);
    small("Generated by the Pega Blueprint POC agent. Figures and content are illustrative.");

    doc.end();
  });
}

export async function buildXlsx(bp: Blueprint): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Pega Blueprint POC";
  wb.created = new Date();

  const s = pega.summary(bp.id);

  // Overview
  const ov = wb.addWorksheet("Overview");
  ov.columns = [
    { header: "Field", key: "k", width: 24 },
    { header: "Value", key: "v", width: 90 },
  ];
  ov.getRow(1).font = { bold: true };
  const rows: [string, string][] = [
    ["Title", bp.title],
    ["Blueprint ID", bp.id],
    ["Industry", bp.industry],
    ["Organization", bp.orgName],
    ["Website", bp.website],
    ["Objective", bp.objective],
    ["Objective details", bp.objectiveDetails],
    ["Language", bp.language],
    ["Location", bp.location],
    ["Products", bp.products.join(", ")],
    ["Outcomes", bp.outcomes.join(", ")],
    ["Channels", bp.channels.join(", ")],
    ["Features", bp.features.join(", ")],
    ["# Actions", String(s.actions)],
    ["# Messages", String(s.treatments)],
    ["# Channels used", String(s.channels)],
  ];
  rows.forEach(([k, v]) => ov.addRow({ k, v }));

  // Personas
  const ps = wb.addWorksheet("Personas");
  ps.columns = [
    { header: "Name", key: "name", width: 24 },
    { header: "Gender", key: "gender", width: 14 },
    { header: "Age band", key: "ageBand", width: 18 },
    { header: "Description", key: "description", width: 100 },
  ];
  ps.getRow(1).font = { bold: true };
  bp.personas.forEach((p) => ps.addRow({ name: p.name, gender: p.gender ?? "", ageBand: p.ageBand ?? "", description: p.description }));

  // Brand voice
  const bv = wb.addWorksheet("Brand Voice");
  bv.columns = [
    { header: "Characteristic", key: "name", width: 28 },
    { header: "Enabled", key: "enabled", width: 12 },
    { header: "Description", key: "description", width: 90 },
  ];
  bv.getRow(1).font = { bold: true };
  bp.voice.forEach((v) => bv.addRow({ name: v.name, enabled: v.enabled ? "Yes" : "No", description: v.description }));

  // Experiences (one row per treatment)
  const ex = wb.addWorksheet("Experiences");
  ex.columns = [
    { header: "Action", key: "action", width: 30 },
    { header: "Product", key: "product", width: 20 },
    { header: "Objective", key: "objective", width: 16 },
    { header: "Treatment", key: "treatment", width: 26 },
    { header: "Channel", key: "channel", width: 14 },
    { header: "Headline", key: "headline", width: 34 },
    { header: "Message", key: "body", width: 60 },
    { header: "CTA", key: "cta", width: 22 },
    { header: "Marketing principle", key: "principle", width: 20 },
  ];
  ex.getRow(1).font = { bold: true };
  for (const a of bp.actions) {
    for (const t of a.treatments) {
      ex.addRow({
        action: a.name, product: a.product, objective: a.objective,
        treatment: t.name, channel: t.channel, headline: t.headline,
        body: t.body, cta: t.cta, principle: t.marketingPrinciple ?? "",
      });
    }
  }

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf as ArrayBuffer);
}
